
easy_admin:
    site_name: '<b>Modulo de asignación</b>'

    list:
        actions:
            - { name: 'new', label: 'Crear %%entity_label%%', icon: 'plus-square', css: 'text-blue'}

    edit:
        title: 'Editando %%entity_label%%'
        actions: ['-delete']
    show:
        actions: ['-delete']
    new:
        title: 'Creacion de %%entity_label%%'

    design:
        menu:
            - { label: 'Dashboard', route: 'dashboard', default: true}
            - { label: 'Horario de sala', entity: 'ClassroomDisplay'}
            - label: 'Asignaciones'
              children: [{ label: 'Asignar a salas', entity: 'SectionCustom'},{ label: 'Asignar a asignaturas', entity: 'ClassroomCustom'},{label: 'Asignaciones Realizadas', entity: 'Allocation'}]
            - label: 'Administracion'
              children: [{label: 'Usuario', entity: 'User'},{label: 'Secciones', entity: 'Section'},{label: 'Facultades', entity: 'Faculty'},{label: 'Departamentos', entity: 'Department'},{ label: 'Facultades y Deptos.', entity: 'FacultyDepartment'},{label: 'Carreras', entity: 'Career'},{label: 'Asignaturas', entity: 'Subject'},{label: 'Profesores', entity: 'Professor'},{label: 'Salas', entity: 'Classroom'}]


    entities:
            Classroom:
                class: App\Entity\Classroom
                label: 'Sala'
                list:
                    title: 'Listado de Salas'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'number', label: 'Numero de sala'}
                        - { property : 'class_size', label: 'Capacidad alumnos'}
                        - { property : 'allocations', label: 'Asignaciones'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'number', label: 'Numero de sala'}
                        - { property : 'class_size', label: 'Capacidad alumnos'}
                new:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'number', label: 'Numero de sala'}
                        - { property : 'class_size', label: 'Capacidad alumnos'}
                templates:
                    list: 'easy_admin/ClassroomListCustom.html.twig'

            Subject:
                class: App\Entity\Subject
                label: 'Asignatura'
                search:
                    fields: ['name', 'code', 'career.name', 'sections']
                list:
                    title: 'Listado de Asignaturas'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo'}
                        - { property : 'career.name', label: 'Carrera'}
                        - { property : 'sections', label: 'Seccion'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo'}
                        - { property : 'career', label: 'Carrera'}
                new:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo'}
                        - { property : 'career', label: 'Carrera'}
                templates:
                     list: 'easy_admin/SubjectListCustom.html.twig'

            Block:
                class: App\Entity\Block
                label: 'Bloque'

            Career:
                class: App\Entity\Career
                label: 'Carrera'
                search:
                    fields: ['name', 'code', 'faculty_department']
                list:
                    title: 'Listado de Carreras'
                    fields:
                        - { property : 'name', label: 'Carrera'}
                        - { property : 'code', label: 'Codigo'}
                        - { property : 'faculty_department', label: 'Facultad y Departamento', type: 'text'}
                        - { property : 'subjects', label: 'Asignaturas'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                     fields:
                              - { property : 'name', label: 'Carrera'}
                              - { property : 'code', label: 'Codigo'}
                              - { property : 'faculty_department', label: 'Facultad y Departamento'}
                new:
                     fields:
                              - { property : 'name', label: 'Carrera'}
                              - { property : 'code', label: 'Codigo'}
                              - { property : 'faculty_department', label: 'Facultad y Departamento'}
                templates:
                      list: 'easy_admin/CareerListCustom.html.twig'


            Faculty:
                class: App\Entity\Faculty
                label: 'Facultad'
                list:
                    title: 'Listado de Facultades'
                    fields:
                        - { property : 'name', label: 'Facultad'}
                        - { property : 'abbreviation', label: 'Abreviacion'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    fields:
                        - { property : 'name', label: 'Facultad'}
                        - { property : 'abbreviation', label: 'Abreviacion'}
                new:
                    fields:
                        - { property : 'name', label: 'Facultad'}
                        - { property : 'abbreviation', label: 'Abreviacion'}
                templates:
                      list: 'easy_admin/FacultyListCustom.html.twig'

            Department:
                class: App\Entity\Department
                label: 'Departamento'
                list:
                    title: 'Listado de Departamentos'
                    fields:
                        - { property : 'name', label: 'Departamento'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    fields:
                        - { property : 'name', label: 'Departamento'}
                new:
                    fields:
                        - { property : 'name', label: 'Departamento'}
                templates:
                      list: 'easy_admin/DepartmentListCustom.html.twig'

            Professor:
                class: App\Entity\Professor
                label: 'Profesor'
                list:
                    title: 'Listado de Profesores'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'lastname', label: 'Apellidos'}
                        - { property : 'sections', label: 'Seccion'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'lastname', label: 'Apellidos'}
                new:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'lastname', label: 'Apellidos'}
                templates:
                      list: 'easy_admin/ProfessorListCustom.html.twig'

            Schedule:
                class: App\Entity\Schedule
                label: 'Horario'

            Section:
                class: App\Entity\Section
                label: 'Sección'
                search:
                      fields: ['name', 'code']
                list:
                    title: 'Lista de %%entity_label%%'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo Seccion'}
                        - { property : 'professor.fullname', label: 'Profesor'}
                        - { property : 'classSize', label: 'Cant. Alumnos'}
                        - { property : 'subject.name', label: 'Asignatura'}
                        - { property : 'FD', label: 'Fac. Depto.'}
                        - { property : 'schedule.abv', label: 'Bloque'}
                        - { property : 'schedule.block.block_time', label: 'Horario'}
                        - { property: 'is_taken', label: 'Asignada?', type: 'boolean'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo seccion'}
                        - { property : 'classSize', type: 'integer' , label: 'Cantidad de alumnos'}
                        - { property : 'subject', label: 'Asignatura'}
                        - { property : 'schedule', label: 'Horario'}
                        - { property : 'professor', label: 'Profesor'}
                new:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo seccion'}
                        - { property : 'classSize', type: 'integer' , label: 'Cantidad de alumnos'}
                        - { property : 'subject', label: 'Asignatura'}
                        - { property : 'schedule', label: 'Horario'}
                        - { property : 'professor', label: 'Profesor'}
                templates:
                    list: 'easy_admin/SectionListCustom.html.twig'

            Weekday:
                class: App\Entity\Weekday
                label: 'Dias de la semana'

            FacultyDepartment:
                class: App\Entity\FacultyDepartment
                label: 'Facultad y Departamento'
                search:
                    fields: ['faculty.name', 'department.name']
                list:
                    title: 'Facultades y Departamentos'
                    fields:
                        - { property : 'faculty.name', label: 'Facultad'}
                        - { property : 'department.name', label: 'Departamento'}
                    actions:
                        - { name: 'edit', icon: 'edit'}
                        - { name: 'delete', icon: 'trash'}
                edit:
                    title: 'Facultades y Departamentos'
                    fields:
                        - { property : 'faculty', label: 'Facultad'}
                        - { property : 'department', label: 'Departamento'}
                new:
                    title: 'Facultades y Departamentos'
                    fields:
                        - { property : 'faculty', label: 'Facultad'}
                        - { property : 'department', label: 'Departamento'}
                templates:
                     list: 'easy_admin/FDListCustom.html.twig'

            SectionCustom:
                class: App\Entity\Section
                label: 'Secciones'
                search:
                      fields: ['name', 'code']
                list:
                    title: 'Lista de %%entity_label%% Disponibles'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo Seccion'}
                        - { property : 'professor.fullname', label: 'Profesor'}
                        - { property : 'classSize', label: 'Cant. Alumnos'}
                        - { property : 'subject.name', label: 'Asignatura'}
                        - { property : 'FD', label: 'Fac. Depto.'}
                        - { property : 'schedule.abv', label: 'Bloque'}
                        - { property : 'schedule.block.block_time', label: 'Horario'}
                    actions:
                        - {name: 'section_allocation', type: 'route',label: 'Asignar' ,icon: 'plus-circle',css_class: 'text-green'}
                        - '-delete'
                        - '-edit'


                    sort: ['name', 'DESC']
                    dql_filter: 'entity.isTaken != true'
                edit:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'code', label: 'Codigo seccion'}
                        - { property : 'classSize', type: 'integer' , label: 'Cantidad de alumnos'}
                        - { property : 'subject', label: 'Asignatura'}
                        - { property : 'schedule', label: 'Horario'}
                        - { property : 'professor', label: 'Profesor'}
                templates:
                    list: 'easy_admin/SectionCustomListCustom.html.twig'



            ClassroomCustom:
                class: App\Entity\Classroom
                label: 'Salas'
                search:
                      fields: ['name', 'code', 'professor.fullname']
                list:
                    title: 'Lista de %%entity_label%% Disponibles'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'number', label: 'Numero de sala'}
                        - { property : 'class_size', label: 'Capacidad alumnos'}
                        - { property : 'allocations', label: 'Asignaciones'}
                    actions:
                        - {name: 'classroom_allocation', type: 'route',label: 'Asignar' ,icon: 'plus-circle',css_class: 'text-green'}
                        - '-show'
                        - '-delete'
                        - '-edit'
                    sort: ['name', 'DESC']
#                                dql_filter: 'entity.isTaken != true'
                edit:
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'number', label: 'Numero de sala'}
                        - { property : 'class_size', label: 'Capacidad alumnos'}
                templates:
                    list: 'easy_admin/ClassroomCustomListCustom.html.twig'

            ClassroomDisplay:
                class: App\Entity\Classroom
                label: 'Salas'
                list:
                    title: 'Seleccion de horario por sala'
                    fields:
                        - { property : 'name', label: 'Nombre'}
                        - { property : 'number', label: 'Numero de sala'}
                        - { property : 'class_size', label: 'Capacidad alumnos'}
                        - { property : 'allocations', label: 'Asignaciones'}
                    actions:
                         - {name: 'classroom_schedule_display', type: 'route',label: 'Ver horario' ,icon: 'search-plus',css_class: 'text-green'}
                         - '-new'
                         - '-edit'
                         - '-delete'
                templates:
                    list: 'easy_admin/ClassroomCustomListCustom.html.twig'
            User:
                class: App\Entity\User
                label: 'Usuarios'
                list:
                    actions:
                          - { name: 'edit', icon: 'edit'}
                          - { name: 'delete', icon: 'trash'}
                form:
                     fields:
                         - {property : 'username', label: 'Nombre_usuario'}
                         - {property : 'email', label: 'Correo'}
                         - {property : 'enabled', label: 'Activo'}
                         # if administrators are allowed to edit users' passwords and roles, add this:
                         - { property : 'plainPassword', type: 'text', type_options: { required: false } }
                         - { property : 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


            Allocation:
                class: App\Entity\Allocation
                label: 'Asignacion'
                list:
                    title: 'Asignaciones'
                    fields:
                        - {property : 'section.code', label: 'Seccion Codigo'}
                        - {property : 'section.name', label: 'Seccion Asignatura'}
                        - {property : 'classroom.number', label: 'Numero sala'}
                        - {property : 'classroom', label: 'Sala'}
                        - {property : 'section.professor', label: 'Profesor'}
                        - {property : 'section.schedule.abv', label: 'Bloque'}
                        - {property : 'section.schedule.block.block_time', label: 'Horario'}
                        - {property : 'classroom.classSize', label: 'Sala cant.'}
                        - {property : 'section.classSize', label: 'Seccion cant.'}
                    actions:
                        - { name: 'delete', icon: 'trash'}
                        - '-edit'

                templates:
                    list: 'easy_admin/AllocationListCustom.html.twig'
            AllocationCustom:
                class: App\Entity\Allocation
                label: 'Asignacion'
